# These are supported funding model platforms

# File requires a github name or else the custom URL won't appear: https://json.schemastore.org/github-funding.json
github: Fdawgs
custom: "https://www.justgiving.com/yeovilhospital"
