services:
    db:
        container_name: ydh-fhir-api-db
        image: mcr.microsoft.com/mssql/server:2019-latest
        environment:
            ACCEPT_EULA: Y
            SA_PASSWORD: Password!
            MSSQL_PID: Express
        ports:
            - 1433:1433
        volumes:
            - ydh-fhir-api-db-data:/var/lib/mssql/data

    app:
        container_name: ydh-fhir-api
        build:
            context: .
        deploy:
            resources:
                limits:
                    cpus: "${DOCKER_APP_CPUS:-0}"
                    memory: "${DOCKER_APP_MEMORY:-0}"
        env_file: .env
        environment:
            DB_CONNECTION_STRING: "Server=ydh-fhir-api-db,1433;Database=master;User Id=sa;Password=Password!;Encrypt=true;TrustServerCertificate=true"
            LOG_ROTATION_DATE_FORMAT:
            LOG_ROTATION_FILENAME:
            NODE_ENV: production
            SERVICE_HOST: 0.0.0.0
        healthcheck:
            test: curl "localhost:${SERVICE_PORT:-8204}/admin/healthcheck"
            interval: 60s
            timeout: 3s
            start_period: 5s
            retries: 3
        labels:
            # Using OCI Image Format spec
            # See https://github.com/opencontainers/image-spec/blob/master/annotations.md
            org.opencontainers.image.authors: Frazer Smith <frazer.smith@ydh.nhs.uk>
            org.opencontainers.image.licenses: MIT
            org.opencontainers.image.url: https://github.com/Fdawgs/ydh-fhir-api
        logging:
            options:
                max-file: "${LOG_ROTATION_MAX_LOGS:-10}"
                max-size: "${LOG_ROTATION_MAX_SIZE:-100m}"
        ports:
            - "127.0.0.1:${SERVICE_PORT:-8204}:${SERVICE_PORT:-8204}"
        restart: "${DOCKER_RESTART_POLICY:-unless-stopped}"

volumes:
    ydh-fhir-api-db-data:
        external: false
